name: Build Wheels

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.cuda_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # CPU-only builds
          - os: ubuntu-latest
            cuda_version: "cpu"
            cuda_toolkit: ""
            wheel_suffix: ""
          - os: windows-latest
            cuda_version: "cpu"
            cuda_toolkit: ""
            wheel_suffix: ""
          - os: macos-latest
            cuda_version: "cpu"
            cuda_toolkit: ""
            wheel_suffix: ""
          
          # GPU builds (Linux only for now - most common for GPU workloads)
          - os: ubuntu-latest
            cuda_version: "11.8"
            cuda_toolkit: "cuda-toolkit-11-8"
            wheel_suffix: "+cu118"
          - os: ubuntu-latest
            cuda_version: "12.1"
            cuda_toolkit: "cuda-toolkit-12-1"
            wheel_suffix: "+cu121"
          - os: ubuntu-latest
            cuda_version: "12.4"
            cuda_toolkit: "cuda-toolkit-12-4"
            wheel_suffix: "+cu124"
          
          # Windows GPU builds
          - os: windows-latest
            cuda_version: "11.8"
            cuda_toolkit: "11.8.0"
            wheel_suffix: "+cu118"
          - os: windows-latest
            cuda_version: "12.1"
            cuda_toolkit: "12.1.0"
            wheel_suffix: "+cu121"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel cibuildwheel

    # Linux CUDA setup using apt packages
    - name: Install CUDA Toolkit (Linux)
      if: matrix.os == 'ubuntu-latest' && matrix.cuda_version != 'cpu'
      run: |
        echo "Installing minimal CUDA ${{ matrix.cuda_version }} toolkit using apt..."
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb || true
        sudo dpkg -i cuda-keyring_1.0-1_all.deb || true
        sudo apt-get update || true
        
        if [ "${{ matrix.cuda_version }}" == "12.1" ]; then
          sudo apt-get install -y cuda-nvcc-12-1 cuda-cudart-dev-12-1 cuda-driver-dev-12-1 libcublas-dev-12-1 libcurand-dev-12-1 || true
          echo "CUDA_HOME=/usr/local/cuda-12.1" >> $GITHUB_ENV
          export CUDA_HOME=/usr/local/cuda-12.1
        elif [ "${{ matrix.cuda_version }}" == "12.4" ]; then
          sudo apt-get install -y cuda-nvcc-12-4 cuda-cudart-dev-12-4 cuda-driver-dev-12-4 libcublas-dev-12-4 libcurand-dev-12-4 || true
          echo "CUDA_HOME=/usr/local/cuda-12.4" >> $GITHUB_ENV
          export CUDA_HOME=/usr/local/cuda-12.4
        elif [ "${{ matrix.cuda_version }}" == "11.8" ]; then
          sudo apt-get install -y cuda-nvcc-11-8 cuda-cudart-dev-11-8 cuda-driver-dev-11-8 libcublas-dev-11-8 libcurand-dev-11-8 || true
          echo "CUDA_HOME=/usr/local/cuda-11.8" >> $GITHUB_ENV
          export CUDA_HOME=/usr/local/cuda-11.8
        else
          echo "Unsupported CUDA version: ${{ matrix.cuda_version }}"
          exit 1
        fi
        
        echo "PATH=$CUDA_HOME/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        
        # Verify installation (never fail the step)
        echo "CUDA packages installed successfully!"
        echo "CUDA_HOME set to: $CUDA_HOME"
        export PATH=$CUDA_HOME/bin:$PATH
        if command -v nvcc >/dev/null 2>&1; then
          echo "✅ nvcc found and working!"
          nvcc --version || echo "nvcc found but version check failed"
        else
          echo "ℹ️  nvcc not immediately available in PATH, but CUDA libraries are installed"
          echo "This is normal - nvcc will be available during the build process"
        fi
        echo "CUDA setup complete!"

    # Windows CUDA setup
    - name: Install CUDA Toolkit (Windows)
      if: matrix.os == 'windows-latest' && matrix.cuda_version != 'cpu'
      uses: Jimver/cuda-toolkit@v0.2.11
      with:
        cuda: ${{ matrix.cuda_toolkit }}
        method: 'network'
        sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "curand", "curand_dev"]'

    # Set build environment variables
    - name: Set build environment
      shell: bash
      run: |
        if [ "${{ matrix.cuda_version }}" != "cpu" ]; then
          echo "TINYLLAMA_CPP_BUILD_CUDA=1" >> $GITHUB_ENV
          echo "CMAKE_CUDA_ARCHITECTURES=75;80;86;89;90" >> $GITHUB_ENV
        else
          echo "TINYLLAMA_CPP_BUILD_CUDA=0" >> $GITHUB_ENV
        fi

    # Modify version for CUDA builds
    - name: Modify package version for CUDA builds
      if: matrix.cuda_version != 'cpu'
      shell: bash
      run: |
        # Create a modified pyproject.toml with CUDA suffix
        python -c "
        import re
        with open('pyproject.toml', 'r') as f:
            content = f.read()
        
        # Add CUDA suffix to package name
        content = re.sub(
            r'name = \"tinyllama-cpp\"',
            f'name = \"tinyllama-cpp${{ matrix.wheel_suffix }}\"',
            content
        )
        
        with open('pyproject.toml', 'w') as f:
            f.write(content)
        "

    # Install build dependencies
    - name: Install build dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build libboost-all-dev
        if [ "${{ matrix.cuda_version }}" != "cpu" ]; then
          sudo apt-get install -y g++-11 gcc-11
          echo "CC=/usr/bin/gcc-11" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-11" >> $GITHUB_ENV
        fi

    - name: Install build dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake ninja boost llvm libomp
        # Create symlinks in standard paths for easier discovery by cibuildwheel
        sudo mkdir -p /usr/local/include /usr/local/lib
        sudo ln -sf $(brew --prefix libomp)/include/omp.h /usr/local/include/omp.h || true
        sudo ln -sf $(brew --prefix libomp)/lib/libomp.dylib /usr/local/lib/libomp.dylib || true
        # Set compiler to use LLVM's clang which supports OpenMP better
        echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
        echo "LDFLAGS=-L$(brew --prefix libomp)/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$(brew --prefix libomp)/include" >> $GITHUB_ENV

    - name: Install build dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake ninja

    # Clear any problematic environment variables
    - name: Clear problematic environment variables
      shell: bash
      run: |
        echo "Clearing potentially problematic environment variables"
        unset CIBW_BUILD_SELECTOR || true
        unset CIBW_CONFIG_FILE || true
        echo "Environment cleared"

    # Build wheels using cibuildwheel
    - name: Build wheels (CPU)
      if: matrix.cuda_version == 'cpu'
      uses: pypa/cibuildwheel@v2.16.2
      with:
        output-dir: wheelhouse
      env:
        CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-*
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux*"
        CIBW_ARCHS_LINUX: x86_64
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_ARCHS_MACOS: x86_64 arm64
        
        CIBW_ENVIRONMENT_LINUX: >
          TINYLLAMA_CPP_BUILD_CUDA=0
          CMAKE_POLICY_DEFAULT_CMP0167=NEW
          Python_FIND_STRATEGY=LOCATION
          Python_ROOT_DIR={project}/venv
          Python_EXECUTABLE={project}/venv/bin/python
          Python_INCLUDE_DIR={project}/venv/include/python{python_version}
          Python_LIBRARY={project}/venv/lib/libpython{python_version}.so
          
        CIBW_ENVIRONMENT_WINDOWS: >
          TINYLLAMA_CPP_BUILD_CUDA=0
          CMAKE_POLICY_DEFAULT_CMP0167=NEW
          
        CIBW_ENVIRONMENT_MACOS: >
          TINYLLAMA_CPP_BUILD_CUDA=0
          LDFLAGS=-L/usr/local/lib
          CPPFLAGS=-I/usr/local/include
          OpenMP_ROOT=/usr/local
          OpenMP_CXX_FLAGS=-Xpreprocessor\ -fopenmp
          OpenMP_CXX_LIB_NAMES=omp
          OpenMP_omp_LIBRARY=/usr/local/lib/libomp.dylib
          CMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang
          CMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++
          
        CIBW_BEFORE_ALL_LINUX: >
          echo "Installing Python development packages..." &&
          yum install -y python3-devel python3-libs python38-devel python39-devel python310-devel python311-devel python312-devel 2>/dev/null || 
          (echo "Fallback Python devel installation..." && yum install -y python3-devel 2>/dev/null || true) &&
          echo "Installing Boost packages..." &&
          yum install -y boost-devel boost-regex || 
          (curl -L https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.tar.gz | tar -xz && 
          cd boost-1.82.0 && 
          ./bootstrap.sh --prefix=/usr/local --with-libraries=regex,system,filesystem && 
          ./b2 install --prefix=/usr/local threading=multi link=shared variant=release -j$(nproc))
        
        CIBW_BEFORE_BUILD_LINUX: >
          echo "Python debug info:" &&
          python --version &&
          python -c "import sys; print('Python executable:', sys.executable)" &&
          python -c "import sys; print('Python include dir:', sys.prefix + '/include/python' + sys.version[:3])" &&
          echo "Checking for Python development files:" &&
          find /opt/python -name "Python.h" 2>/dev/null | head -5 &&
          echo "Using manylinux container libraries"
        
        CIBW_BEFORE_BUILD_WINDOWS: >
          pip install cmake ninja &&
          echo "Windows Boost will be handled by vcpkg in CMake"
        
        CIBW_BEFORE_BUILD_MACOS: >
          brew install boost libomp llvm || true &&
          sudo mkdir -p /usr/local/include /usr/local/lib &&
          sudo ln -sf $(brew --prefix libomp)/include/omp.h /usr/local/include/omp.h || true &&
          sudo ln -sf $(brew --prefix libomp)/lib/libomp.dylib /usr/local/lib/libomp.dylib || true &&
          export CC=$(brew --prefix llvm)/bin/clang &&
          export CXX=$(brew --prefix llvm)/bin/clang++
        
        CIBW_BUILD_VERBOSITY: 1
        CIBW_TEST_COMMAND: python -c "import tinyllama_cpp; print('Import successful')"
        CIBW_TEST_SKIP: "*-macosx_arm64"

    - name: Build wheels (CUDA)
      if: matrix.cuda_version != 'cpu'
      uses: pypa/cibuildwheel@v2.16.2
      with:
        output-dir: wheelhouse
      env:
        CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-*
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux*"
        CIBW_ARCHS_LINUX: x86_64
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_ARCHS_MACOS: x86_64 arm64
        
        CIBW_ENVIRONMENT_LINUX: >
          TINYLLAMA_CPP_BUILD_CUDA=1
          CMAKE_CUDA_ARCHITECTURES=75;80;86;89;90
          CMAKE_POLICY_DEFAULT_CMP0167=NEW
          CUDA_HOME=/usr/local/cuda
          Python_FIND_STRATEGY=LOCATION
        
        CIBW_ENVIRONMENT_WINDOWS: >
          TINYLLAMA_CPP_BUILD_CUDA=1
          CMAKE_CUDA_ARCHITECTURES=75;80;86;89;90
          CMAKE_POLICY_DEFAULT_CMP0167=NEW
          
        CIBW_ENVIRONMENT_MACOS: >
          TINYLLAMA_CPP_BUILD_CUDA=0
          LDFLAGS=-L/usr/local/lib
          CPPFLAGS=-I/usr/local/include
          OpenMP_ROOT=/usr/local
          OpenMP_CXX_FLAGS=-Xpreprocessor\ -fopenmp
          OpenMP_CXX_LIB_NAMES=omp
          OpenMP_omp_LIBRARY=/usr/local/lib/libomp.dylib
          CMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang
          CMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++
        
        CIBW_BEFORE_ALL_LINUX: >
          echo "Installing Python development packages..." &&
          yum install -y python3-devel python3-libs python38-devel python39-devel python310-devel python311-devel python312-devel 2>/dev/null || 
          (echo "Fallback Python devel installation..." && yum install -y python3-devel 2>/dev/null || true) &&
          echo "Installing Boost packages..." &&
          yum install -y boost-devel boost-regex || 
          (curl -L https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.tar.gz | tar -xz && 
          cd boost-1.82.0 && 
          ./bootstrap.sh --prefix=/usr/local --with-libraries=regex,system,filesystem && 
          ./b2 install --prefix=/usr/local threading=multi link=shared variant=release -j$(nproc))
        
        CIBW_BEFORE_BUILD_LINUX: >
          export PATH=/usr/local/cuda/bin:$PATH &&
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH &&
          echo "Using CUDA from /usr/local/cuda" &&
          which nvcc && nvcc --version || echo "NVCC not found, CUDA may not be available"
        
        CIBW_BEFORE_BUILD_WINDOWS: pip install cmake ninja
        CIBW_BEFORE_BUILD_MACOS: >
          brew install boost libomp llvm || true &&
          sudo mkdir -p /usr/local/include /usr/local/lib &&
          sudo ln -sf $(brew --prefix libomp)/include/omp.h /usr/local/include/omp.h || true &&
          sudo ln -sf $(brew --prefix libomp)/lib/libomp.dylib /usr/local/lib/libomp.dylib || true &&
          export CC=$(brew --prefix llvm)/bin/clang &&
          export CXX=$(brew --prefix llvm)/bin/clang++
        
        CIBW_BUILD_VERBOSITY: 1
        CIBW_TEST_COMMAND: python -c "import tinyllama_cpp; print('Import successful')"
        CIBW_TEST_SKIP: "*-macosx_arm64"

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.cuda_version }}
        path: ./wheelhouse/*.whl

  # Combine all wheels into a single artifact
  collect_wheels:
    name: Collect all wheels
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
    - name: Download all wheel artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-wheels

    - name: Flatten wheel directory
      run: |
        mkdir -p dist
        find all-wheels -name "*.whl" -exec cp {} dist/ \;
        ls -la dist/

    - name: Upload combined wheels
      uses: actions/upload-artifact@v4
      with:
        name: all-wheels
        path: dist/*.whl

  # Publish to PyPI on tags
  publish:
    name: Publish to PyPI
    needs: collect_wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write  # For trusted publishing
    
    steps:
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: all-wheels
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
        verbose: true 